version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/fadi12321/test-for-deep-8"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"